name: Update Blox Fruits Data

on:
  schedule:
    - cron: '0 * * * *'  # Запуск кожну годину
  workflow_dispatch:      # Дозволяє запускати вручну

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run scraper
      run: python scraper/scraper.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add api/data/bloxfruits.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Blox Fruits data" && git push)
